dataset: 'animal'
data_folder: "data"
output_folder: 'smpl_debug'
prior_folder: 'priors'
model_folder: 'models'
result_folder: 'results'
model_type: 'smpl'
# Flag for using the GPU
use_cuda: False
float_dtype: "float32"
use_joints_conf: True
use_pca: True
use_hands: False
use_face: False
flat_hand_mean: False
# The number of mixture components for the pose prior
num_gaussians: 8
#body_prior_type: 'l2'
body_prior_type: 'mahalanobis_body_prior'
left_hand_prior_type: l2
right_hand_prior_type: l2
focal_length: 1000 # °°°°°°° was 5000
num_pca_comps: 12
# The constant for the robust loss function
rho: 100
interpenetration: False
df_cone_height: 0.0001
# Upper arms and Spine 2
# Neck and jaw
ign_part_pairs: ["9,16", "9,17", "6,16", "6,17", "1,2", "12,22"]
penalize_outside: True
max_collisions: 128
# LBFGS with line search
optim_type: 'lbfgs'
#optim_type: 'lbfgsls'
ftol: 1e-9
gtol: 1e-9
lr: 0.1 # °°°°°° 1.0
# Max number of optimization iterations
maxiters: 15 #°°°°°° 30
interactive: True
visualize: False

data_weights:
    - 1.5e3
#    - 1.5e3
#    - 1.5e3
#    - 1.5e3
body_pose_prior_weights:
    - 2.0e4
#    - 1.6e4
#    - 1.0e4
#    - 0.98e4
shape_weights:
#    - 1e2
#    - .9e2
#    - .7e2
#    - .6e2
    - 1e4
#    - .9e4
#    - .7e4
#    - .6e4

use_vposer: False
vposer_ckpt: "vposer"
