dataset: 'video_animal'
data_folder: "data"
prior_folder: 'priors'
model_type: 'smpl'
use_cuda: False
use_joints_conf: True
use_pca: True
use_hands: False
use_face: False
flat_hand_mean: False
# The number of mixture components for the pose prior
num_gaussians: 8
body_prior_type: 'mahalanobis_body_prior'
left_hand_prior_type: l2
right_hand_prior_type: l2
focal_length: 800 #1054 #1436 #4162 # °°°°°°° was 5000
num_pca_comps: 12
# The constant for the robust loss function
rho: 150
interpenetration: False
df_cone_height: 0.0001
# Upper arms and Spine 2
# Neck and jaw
ign_part_pairs: ["9,16", "9,17", "6,16", "6,17", "1,2", "12,22"]
penalize_outside: True
max_collisions: 128
# LBFGS with line search
#optim_type: 'lbfgs'
optim_type: 'adam'
ftol: 1e-9
gtol: 1e-9
lr: 0.03 # °°°°°° 1.0
# Max number of optimization iterations
maxiters: 50 #°°°°°° 30
interactive: True
visualize: True

data_weights:
    - 5.0e2
#    - 1.5e3
#    - 1.5e3
#    - 1.5e3
body_pose_prior_weights:
    - 1.5e3
#    - 1.6e4
#    - 1.0e4
#    - 0.98e4
shape_weights:
#    - 1e2
#    - .9e2
#    - .7e2
#    - .6e2
    - 0.5e1
#    - .9e4
#    - .7e4
#    - .6e4

use_vposer: False
vposer_ckpt: "/home/frg08/Code/smplify-x/V02_05/"
zebra_betas: [4.01370676e-01, 1.23658677e+00, -8.94257279e-01,
             3.19973349e-01, 7.19024035e-01, -1.05410595e-01,
             3.99230129e-01, 1.58862240e-01, 3.85614217e-01,
             -8.16620447e-02, 1.46995142e-01, -2.31515581e-01,
             -3.10253925e-01, -3.42558453e-01, -2.16503877e-01,
             4.97941459e-02, 8.76565450e-03, 1.12414110e-01,
             9.20290504e-02, 5.10690930e-02]
num_betas: 20

use_yaw: True